[package]
name = "news-feed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
feed-rs = "1.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }